### ISSUE TITLE
post_process

### ISSUE THREAD

**Issue by zhangyuelong** [ArayCHN/VPGNet_for_lane#10]
1) I recompile your all files in VPGNet/VPGNet_for_lane-master/caltech-lanes-dataset/caltech-lane-detection/src using swig.sh, then i make makefile and generate LaneDetector64 , but　ｉdon't know  how to use LaneDetector64?could you help me?   or i only  run ./LaneDetector64 but then opencv error ,but my opencv is not error in fact.
2）I run test case python lane_extension_polyline_for_VPG.py list/input.png -a -o -d output_log then generate well results.
3) I wish we can communicate in Chinese.thanks

**Comment by kpaonaut** [comment]
You don't have to do anything with `LaneDetector64`. It is just some middle file generated by swig for py-c++ interface. Just call `python lane_extension_polyline_for_MultiNet.py` after sourcing `swig.sh` and you should be fine.

你不需要做makefile等一系列事情。`LaneDetector64`只是swig产生的中间文件。按照我在首页README写的顺序来做就可以了。首先`source swig.sh`，然后运行`python lane_extension_polyline_for_MultiNet.py`就可以。具体这个文件做了哪些事情，代码都在python文件里，建议去看一下源代码。

**Comment by zhangyuelong** [comment]
谢谢了

**Comment by zhangyuelong** [comment]
您好，还有两个疑惑：
1.向您确认一下VPGNet文中所述的道路标识分类所使用的数据库应该是文献34的吧？http://www.ananth.in/RoadMarkingDetection.html
2.我想将车道线与道路标识分类一起训练，车道线数据库和道路标识数据库怎么组合比较好？
　直接将标签数据放到一个txt中然后生成lmdb格式文件可以吗？

**Comment by kpaonaut** [comment]
抱歉之前没看到消息。

1.我其实不清楚，我自己训的时候用的是caltech数据库。
2.就这个repo里面的代码而言，不同的任务应该不能一起训练，除非你的数据库里每张图片都同时标注了车道线和路牌的标签。另外，即使这样，如果要混在一起训练，我个人认为会存在数据bias，需要进行额外的数据加强操作。但是具体训练细节就beyond the scope of this repository了，建议单独去做一些research，在这里就不仔细讨论了。
