### ISSUE TITLE
TODO-for-new_lane_extension_for_VPG

### ISSUE THREAD

**Issue by ArayCHN** [ArayCHN/VPGNet_for_lane#7]
1. check if ground coordinates are correct.
2. optimize code - currently 0.01s, still too slow - should be faster than lane_extension_for_MultiNet!
3. Integrating all code into a single python code; delete lane_extension_for_VPG.py.
4. test workflow with trained VPGNet! (and timing!)

**Comment by pengyiwu** [comment]
Thanks for sharing your code. 我对后处理部分很感兴趣，但是我的语义分割部分全部使用python编写，so不太会用您的代码，cluster前应该需要一次采样来精简像素（cluster完后再拟合），请问有没有什么好的方法。

**Comment by ArayCHN** [comment]
> Thanks for sharing your code. 我对后处理部分很感兴趣，但是我的语义分割部分全部使用python编写，so不太会用您的代码，cluster前应该需要一次采样来精简像素（cluster完后再拟合），请问有没有什么好的方法。

感谢你的兴趣\&提问。

* 我的post-processing是先用houghlines算法寻找直线，再进行聚类（在readme里有写）。聚类是用的hierarchical clustering，是常见的聚类方法，用了scipy提供的接口。

* 代码使用方法在readme中有，c++只是写了一个辅助的库，整个程序的接口可以完全通过python调用（但在不同电脑上可能需要对c++文件进行编译）。因为这个仓库是六个月之前写的，已经不再维护，请根据使用方法寻找一下相关文件，如果想了解实现细节还是需要阅读源代码。

* 问题似乎和此条issue不相关，如果有其他问题请开新issue，不要在这个issue底下回复。
